https://docs.google.com/presentation/d/1X0POtQcf0E8ffCSL-f01tw5JBSP4Tsusn4pHr7eLajk/edit?usp=sharing

In [1]:
from torch import nn
import torch
from torch import tensor

# Import Data

In [2]:
x_data = tensor([[1.0], [2.0], [3.0]])
y_data = tensor([[2.0], [4.0], [6.0]])

# Step1: Model Design
Design your model using class with Variables

$ \hat{y} = x * w + b$  

$ \hat{y} = x * w$

In [3]:
# https://pytorch.org/docs/stable/generated/torch.nn.Linear.html
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()        
        # One in and one out, linear model
        # Linear(x, y)->x: input size, y: output size
        self.linear = torch.nn.Linear(1, 1)
        # self.linear = torch.nn.Linear(1, 1, bias=False)

    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

In [4]:
# model object
model = Model()

# Step2: Construct loss and optimizer 
## Loss Function

In [5]:
# https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html
# loss function: Mean Square Error
# criterion: 표준, 척도, 기준
criterion = torch.nn.MSELoss(reduction='sum')

## Optimizer

In [6]:
# https://pytorch.org/docs/stable/_modules/torch/optim/sgd.html
# optimizer가 최적화 하기 위한 model의 weight를 불러오기: model.parameters()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [7]:
optimizer.param_groups

[{'params': [Parameter containing:
   tensor([[0.0553]], requires_grad=True),
   Parameter containing:
   tensor([-0.4102], requires_grad=True)],
  'lr': 0.01,
  'momentum': 0,
  'dampening': 0,
  'weight_decay': 0,
  'nesterov': False}]

# Step3: Train Model
forward, backward, update

In [8]:
# Training loop
for epoch in range(100):
    # 1) Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)

    # 2) Compute and print loss
    loss = criterion(y_pred, y_data)
    print(f'Epoch: {epoch} | Loss: {loss.item()} ')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()  # initialize all gradients
    loss.backward()
    optimizer.step()

Epoch: 0 | Loss: 63.021419525146484 
Epoch: 1 | Loss: 28.087722778320312 
Epoch: 2 | Loss: 12.535772323608398 
Epoch: 3 | Loss: 5.612023830413818 
Epoch: 4 | Loss: 2.529315948486328 
Epoch: 5 | Loss: 1.1565362215042114 
Epoch: 6 | Loss: 0.5449754595756531 
Epoch: 7 | Loss: 0.2722926437854767 
Epoch: 8 | Loss: 0.1504753828048706 
Epoch: 9 | Loss: 0.0958254262804985 
Epoch: 10 | Loss: 0.07108239829540253 
Epoch: 11 | Loss: 0.05965880677103996 
Epoch: 12 | Loss: 0.05417090654373169 
Epoch: 13 | Loss: 0.0513310581445694 
Epoch: 14 | Loss: 0.049675531685352325 
Epoch: 15 | Loss: 0.048553191125392914 
Epoch: 16 | Loss: 0.04767347127199173 
Epoch: 17 | Loss: 0.04690738767385483 
Epoch: 18 | Loss: 0.04619721695780754 
Epoch: 19 | Loss: 0.04551728069782257 
Epoch: 20 | Loss: 0.04485594108700752 
Epoch: 21 | Loss: 0.04420807957649231 
Epoch: 22 | Loss: 0.043571364134550095 
Epoch: 23 | Loss: 0.0429445281624794 
Epoch: 24 | Loss: 0.04232700914144516 
Epoch: 25 | Loss: 0.04171866178512573 
Epoch: 

In [9]:
for name, param in model.named_parameters():
    print(name, param)

linear.weight Parameter containing:
tensor([[1.9204]], requires_grad=True)
linear.bias Parameter containing:
tensor([0.1809], requires_grad=True)


# Predict Value

In [10]:
# After training
hour_var = tensor([[4.0]])
y_pred = model(hour_var)
print("Prediction (after training)",  4, model(hour_var).data[0][0].item())

Prediction (after training) 4 7.8625712394714355
