https://docs.google.com/presentation/d/1X0POtQcf0E8ffCSL-f01tw5JBSP4Tsusn4pHr7eLajk/edit?usp=sharing

In [1]:
import torch
from torch import tensor
from torch import nn
from torch import sigmoid
import torch.nn.functional as F
import torch.optim as optim

# Import Data

In [2]:
x_data = tensor([[1.0], [2.0], [3.0], [4.0]])
y_data = tensor([[0.0], [0.0], [1.0], [1.0]])

# Step1: Model Design
Design your model using class with Variables

$ \hat{y} = \sigma(x * w + b)$  

In [3]:
class Model(nn.Module):
    def __init__(self):

        super(Model, self).__init__()
        # One in and one out, linear model
        # Linear(x, y)->x: input size, y: output size
        self.linear = nn.Linear(1, 1)  # One in and one out

    def forward(self, x):
        y_pred = sigmoid(self.linear(x))  # different point btw classification and regression
        return y_pred

In [4]:
# model object
model = Model()

# Step2: Construct loss and optimizer 
## Loss Function

In [5]:
# https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html
# loss function: Binary Cross Entropy
# criterion: 표준, 척도, 기준
criterion = torch.nn.BCELoss(reduction='mean')  # different point btw classification and regression

## Optimizer

In [6]:
# https://pytorch.org/docs/stable/_modules/torch/optim/sgd.html
# optimizer가 최적화 하기 위한 model의 weight를 불러오기: model.parameters()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [7]:
optimizer.param_groups

[{'params': [Parameter containing:
   tensor([[-0.2511]], requires_grad=True),
   Parameter containing:
   tensor([0.5059], requires_grad=True)],
  'lr': 0.01,
  'momentum': 0,
  'dampening': 0,
  'weight_decay': 0,
  'nesterov': False}]

# Step3: Train Model
forward, backward, update

In [8]:
# Training loop
for epoch in range(1000):
    # 1) Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)

    # 2) Compute and print loss
    loss = criterion(y_pred, y_data)
    if epoch % 10 == 0:
        print(f'Epoch: {epoch} | Loss: {loss.item()} ')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()  # initialize all gradients
    loss.backward()
    optimizer.step()

Epoch: 0 | Loss: 0.8303244709968567 
Epoch: 10 | Loss: 0.7944744825363159 
Epoch: 20 | Loss: 0.7697370648384094 
Epoch: 30 | Loss: 0.7523869276046753 
Epoch: 40 | Loss: 0.7398848533630371 
Epoch: 50 | Loss: 0.7305552363395691 
Epoch: 60 | Loss: 0.723307728767395 
Epoch: 70 | Loss: 0.7174354195594788 
Epoch: 80 | Loss: 0.712478756904602 
Epoch: 90 | Loss: 0.7081379890441895 
Epoch: 100 | Loss: 0.7042156457901001 
Epoch: 110 | Loss: 0.7005813121795654 
Epoch: 120 | Loss: 0.6971482038497925 
Epoch: 130 | Loss: 0.6938580274581909 
Epoch: 140 | Loss: 0.6906715631484985 
Epoch: 150 | Loss: 0.6875623464584351 
Epoch: 160 | Loss: 0.6845123767852783 
Epoch: 170 | Loss: 0.6815094351768494 
Epoch: 180 | Loss: 0.6785447597503662 
Epoch: 190 | Loss: 0.67561274766922 
Epoch: 200 | Loss: 0.6727093458175659 
Epoch: 210 | Loss: 0.6698317527770996 
Epoch: 220 | Loss: 0.6669779419898987 
Epoch: 230 | Loss: 0.6641466617584229 
Epoch: 240 | Loss: 0.6613367795944214 
Epoch: 250 | Loss: 0.658547580242157 
Ep

In [9]:
for name, param in model.named_parameters():
    print(name, param)

linear.weight Parameter containing:
tensor([[0.5522]], requires_grad=True)
linear.bias Parameter containing:
tensor([-0.8418], requires_grad=True)


# Predict Value

In [10]:
# After training
print(f'\nLet\'s predict the hours need to score above 50%\n{"=" * 50}')
hour_var = model(tensor([[1.0]]))
print(f'Prediction after 1 hour of training: {hour_var.item():.4f} | Above 50%: {hour_var.item() > 0.5}')
hour_var = model(tensor([[7.0]]))
print(f'Prediction after 7 hours of training: {hour_var.item():.4f} | Above 50%: { hour_var.item() > 0.5}')


Let's predict the hours need to score above 50%
Prediction after 1 hour of training: 0.4281 | Above 50%: False
Prediction after 7 hours of training: 0.9536 | Above 50%: True
