https://docs.google.com/presentation/d/1X0POtQcf0E8ffCSL-f01tw5JBSP4Tsusn4pHr7eLajk/edit?usp=sharing

In [1]:
import torch
from torch import tensor
from torch import nn
from torch import sigmoid
import torch.nn.functional as F
import torch.optim as optim

# Import Data

In [2]:
x_data = tensor([[1.0, 1.0], [2.0, 2.0], [3.0, 3.0], [4.0, 4.0]])
y_data = tensor([[0.0], [0.0], [1.0], [1.0]])

# Step1: Model Design
Design your model using class with Variables

In [3]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.l1 = nn.Linear(2, 8)
        self.l2 = nn.Linear(8, 4)
        self.l3 = nn.Linear(4, 1)

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out1 = self.sigmoid(self.l1(x))
        out2 = self.sigmoid(self.l2(out1))
        y_pred = self.sigmoid(self.l3(out2))
        return y_pred

In [4]:
# model object
model = Model()

# Step2: Construct loss and optimizer 
## Loss Function

In [5]:
# https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html
# loss function: Binary Cross Entropy
# criterion: 표준, 척도, 기준
criterion = torch.nn.BCELoss(reduction='mean')

## Optimizer

In [6]:
# https://pytorch.org/docs/stable/_modules/torch/optim/sgd.html
# optimizer가 최적화 하기 위한 model의 weight를 불러오기: model.parameters()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [7]:
optimizer.param_groups

[{'params': [Parameter containing:
   tensor([[ 0.5607,  0.1043],
           [-0.2488,  0.1685],
           [ 0.4926, -0.1143],
           [-0.1776, -0.6852],
           [-0.6467,  0.1777],
           [-0.6357, -0.4836],
           [ 0.5711, -0.3857],
           [-0.7014,  0.1710]], requires_grad=True),
   Parameter containing:
   tensor([ 0.4226,  0.5252, -0.4828, -0.6886,  0.6029,  0.0511, -0.4826,  0.2328],
          requires_grad=True),
   Parameter containing:
   tensor([[ 0.0752, -0.3432,  0.0415,  0.2159,  0.2153,  0.3030, -0.2429,  0.0909],
           [ 0.2999,  0.0992,  0.3121, -0.1255, -0.1520,  0.2752,  0.2651, -0.0637],
           [ 0.2646, -0.1300,  0.0889,  0.1785,  0.3507, -0.2267, -0.1716,  0.2120],
           [ 0.2424, -0.3236, -0.2297,  0.0082, -0.0793,  0.0473, -0.2193,  0.2142]],
          requires_grad=True),
   Parameter containing:
   tensor([-0.0982, -0.0648, -0.2138,  0.0363], requires_grad=True),
   Parameter containing:
   tensor([[ 0.1885,  0.0142, -0.0128, 

# Step3: Train Model
forward, backward, update

In [8]:
# Training loop
for epoch in range(1000):
    # 1) Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)

    # 2) Compute and print loss
    loss = criterion(y_pred, y_data)
    if epoch % 10 == 0:
        print(f'Epoch: {epoch} | Loss: {loss.item()} ')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()  # initialize all gradients
    loss.backward()
    optimizer.step()

Epoch: 0 | Loss: 0.6957485675811768 
Epoch: 10 | Loss: 0.6952481269836426 
Epoch: 20 | Loss: 0.6948761940002441 
Epoch: 30 | Loss: 0.6945563554763794 
Epoch: 40 | Loss: 0.694261908531189 
Epoch: 50 | Loss: 0.6939830183982849 
Epoch: 60 | Loss: 0.6937153935432434 
Epoch: 70 | Loss: 0.693456768989563 
Epoch: 80 | Loss: 0.6932055950164795 
Epoch: 90 | Loss: 0.6929605603218079 
Epoch: 100 | Loss: 0.6927204132080078 
Epoch: 110 | Loss: 0.6924841403961182 
Epoch: 120 | Loss: 0.6922507286071777 
Epoch: 130 | Loss: 0.6920188665390015 
Epoch: 140 | Loss: 0.6917877793312073 
Epoch: 150 | Loss: 0.6915562748908997 
Epoch: 160 | Loss: 0.6913236379623413 
Epoch: 170 | Loss: 0.6910886168479919 
Epoch: 180 | Loss: 0.6908501982688904 
Epoch: 190 | Loss: 0.6906076669692993 
Epoch: 200 | Loss: 0.6903599500656128 
Epoch: 210 | Loss: 0.6901059150695801 
Epoch: 220 | Loss: 0.6898446679115295 
Epoch: 230 | Loss: 0.6895751357078552 
Epoch: 240 | Loss: 0.6892964839935303 
Epoch: 250 | Loss: 0.6890071630477905 

In [9]:
for name, param in model.named_parameters():
    print(name, param)

l1.weight Parameter containing:
tensor([[ 0.5225,  0.0661],
        [-0.6033, -0.1861],
        [ 0.6640,  0.0571],
        [-0.0482, -0.5558],
        [-0.8506, -0.0261],
        [-0.5122, -0.3601],
        [ 0.8098, -0.1470],
        [-0.7893,  0.0831]], requires_grad=True)
l1.bias Parameter containing:
tensor([ 0.1192,  0.9528, -0.7139, -0.4539,  1.3028,  0.1835, -0.6035,  0.5911],
       requires_grad=True)
l2.weight Parameter containing:
tensor([[ 0.0347, -0.1961, -0.0445,  0.2715,  0.3603,  0.3753, -0.3192,  0.1951],
        [ 0.4353, -0.5388,  0.6384, -0.4232, -0.8857, -0.1261,  0.4456, -0.6349],
        [-0.0147,  0.4618, -0.3609,  0.4569,  1.0343,  0.1521, -0.4735,  0.7374],
        [ 0.7651, -1.3230,  0.5703, -0.4893, -1.2840, -0.6355,  0.2640, -0.7285]],
       requires_grad=True)
l2.bias Parameter containing:
tensor([-0.0672, -0.3256, -0.1276, -0.0994], requires_grad=True)
l3.weight Parameter containing:
tensor([[-0.5404,  1.4052, -1.5717,  2.2539]], requires_grad=True)
l3.

# Predict Value

In [10]:
# After training
print(f'\nLet\'s predict the hours need to score above 50%\n{"=" * 50}')
hour_var = model(tensor([[1.0, 1.0]]))
print(f'Prediction after 1 hour of training: {hour_var.item():.4f} | Above 50%: {hour_var.item() > 0.5}')
hour_var = model(tensor([[7.0, 7.0]]))
print(f'Prediction after 7 hours of training: {hour_var.item():.4f} | Above 50%: { hour_var.item() > 0.5}')


Let's predict the hours need to score above 50%
Prediction after 1 hour of training: 0.2213 | Above 50%: False
Prediction after 7 hours of training: 0.8085 | Above 50%: True
